"""Add product category and dimensions

Revision ID: bac04e755bc7
Revises: 7240122c0000
Create Date: 2026-06-21 07:15:57.602092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bac04e755bc7'
down_revision: Union[str, None] = '7240122c0000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category', sa.String(length=100), nullable=False))
    op.add_column('products', sa.Column('weight', sa.Numeric(precision=10, scale=3), nullable=False))
    op.add_column('products', sa.Column('length', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('products', sa.Column('breadth', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('products', sa.Column('height', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'height')
    op.drop_column('products', 'breadth')
    op.drop_column('products', 'length')
    op.drop_column('products', 'weight')
    op.drop_column('products', 'category')
    # ### end Alembic commands ###
